name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_options: "--no-cache --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} --build-arg EXPRESS_PORT=${{ secrets.EXPRESS_PORT }} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }}"
          process_type: web
